// This file is auto-generated by TanStack Router

import { FileRoute, lazyRouteComponent } from "@tanstack/react-router";

// Import Routes

import { Route as rootRoute } from "./routes/__root";

// Create Virtual Routes

const PlayersComponentImport = new FileRoute("/players").createRoute();
const IndexComponentImport = new FileRoute("/").createRoute();

// Create/Update Routes

const PlayersComponentRoute = PlayersComponentImport.update({
  path: "/players",
  getParentRoute: () => rootRoute,
} as any).update({
  component: lazyRouteComponent(
    () => import("./routes/players.component"),
    "component"
  ),
});

const IndexComponentRoute = IndexComponentImport.update({
  path: "/",
  getParentRoute: () => rootRoute,
} as any).update({
  component: lazyRouteComponent(
    () => import("./routes/index.component"),
    "component"
  ),
});

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      preLoaderRoute: typeof IndexComponentImport;
      parentRoute: typeof rootRoute;
    };
    "/players": {
      preLoaderRoute: typeof PlayersComponentImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexComponentRoute,
  PlayersComponentRoute,
]);
